import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  employees: [
    {
      firstName: 'Garrett',
      lastName: 'Hedman',
      startDate: '10/24/2023',
      street: '81694 Columbus Park',
      dateOfBirth: '5/6/2024',
      department: 'Sales',
      city: 'Cincinnati',
      state: 'OH',
      zipCode: '45218',
    },
    {
      firstName: 'Colette',
      lastName: 'Jakuszewski',
      startDate: '2/1/2023',
      street: '76 Brickson Park Pass',
      dateOfBirth: '7/24/2015',
      department: 'Human Resources',
      city: 'Monroe',
      state: 'LA',
      zipCode: '71208',
    },
    {
      firstName: 'Allegra',
      lastName: 'Baggett',
      startDate: '5/21/2024',
      street: '47 Monterey Hill',
      dateOfBirth: '5/26/1992',
      department: 'Sales',
      city: 'Pensacola',
      state: 'FL',
      zipCode: '32511',
    },
    {
      firstName: 'Clio',
      lastName: 'Regnard',
      startDate: '2/1/2024',
      street: '387 Farragut Court',
      dateOfBirth: '12/5/2015',
      department: 'Legal',
      city: 'Mobile',
      state: 'AL',
      zipCode: '36641',
    },
    {
      firstName: 'Ranice',
      lastName: 'Gudyer',
      startDate: '4/13/2023',
      street: '8 Schmedeman Drive',
      dateOfBirth: '1/16/2005',
      department: 'Marketing',
      city: 'New York City',
      state: 'NY',
      zipCode: '10260',
    },
    // {
    //   firstName: 'Celestine',
    //   lastName: 'Calterone',
    //   startDate: '10/13/2022',
    //   street: '9809 Dwight Trail',
    //   dateOfBirth: '1/24/2004',
    //   department: 'Marketing',
    //   city: 'Gadsden',
    //   state: 'AL',
    //   zipCode: '35905',
    // },
    // {
    //   firstName: 'Enid',
    //   lastName: 'Firk',
    //   startDate: '4/5/2023',
    //   street: '0633 Chive Junction',
    //   dateOfBirth: '10/7/2006',
    //   department: 'Legal',
    //   city: 'Atlanta',
    //   state: 'GA',
    //   zipCode: '30336',
    // },
    // {
    //   firstName: 'Andros',
    //   lastName: 'Heinig',
    //   startDate: '2/13/2022',
    //   street: '2163 Waxwing Pass',
    //   dateOfBirth: '9/9/1994',
    //   department: 'Engineering',
    //   city: 'Houston',
    //   state: 'TX',
    //   zipCode: '77299',
    // },
    // {
    //   firstName: 'Myrtle',
    //   lastName: 'Poleye',
    //   startDate: '11/16/2022',
    //   street: '1506 Oakridge Road',
    //   dateOfBirth: '3/18/2005',
    //   department: 'Marketing',
    //   city: 'Lake Charles',
    //   state: 'LA',
    //   zipCode: '70616',
    // },
    // {
    //   firstName: 'Megan',
    //   lastName: 'Mote',
    //   startDate: '8/29/2023',
    //   street: '82801 Golden Leaf Way',
    //   dateOfBirth: '10/27/2023',
    //   department: 'Sales',
    //   city: 'Denver',
    //   state: 'CO',
    //   zipCode: '80235',
    // },
  ],
};

export const employeeSlice = createSlice({
  name: 'employee',
  initialState,
  reducers: {
    createEmployee: (state, action) => {
      state.employees.push(action.payload);
    },
  },
});

export const { createEmployee } = employeeSlice.actions;
export default employeeSlice.reducer;
